services:
  db:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'loan_service'
      MYSQL_USER: 'yu71'
      MYSQL_PASSWORD: '53cret'
      MYSQL_ROOT_PASSWORD: '53cret'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
volumes:
  my-db:
